import styled from "styled-components";
export const ParentContainer = styled.div``;
export const ParentBox = styled.div``;
export const ParentTitle = styled.h1``;
export const ParentBody = styled.div``;
export const ParentDescription = styled.p``;
export const ParentForm = styled.form``;
export const ParentFormInput = styled.input``;
export const ParentQuestionBox = styled.div``;
export const ParentQuestion = styled.p``;
export const ParentSubmitButton = styled.button``;
export const ParentGalleryButton = styled.a``;
